version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - portfolio-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - portfolio-redis:/var/lib/redis/data

  portfolio:
    build:
      context: .
    volumes:
      - .:/app
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    environment:
      - RAILS_ENV=development
      # - DATABASE_URL=postgresql://portfolio:test_db_password@postgres:5432/portfolio?encoding=utf8&pool=5&timeout=5000
      - DATABASE_HOST=postgres
      - DATABASE_NAME=portfolio_development
      - DATABASE_USERNAME=portfolio
      - DATABASE_PASSWORD=test_db_password
      - CACHE_URL=redis://redis:6379/0
      - JOB_WORKER_URL=redis://redis:6379/0

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    environment:
      - JOB_WORKER_URL=redis://redis:6379/0

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - portfolio
    ports:
      - '8020:8020'

volumes:
  portfolio-postgres:
  portfolio-redis: