
development:
  url: <%= ENV.fetch("DEVELOPMENT_DATABASE_URL","?").gsub('?', '_development?') %>

test:
  url: <%= ENV.fetch("DEVELOPMENT_DATABASE_URL","?").gsub('?', '_test?') %>

staging:
  url: <%= ENV.fetch("DEVELOPMENT_DATABASE_URL","?").gsub('?', '_staging?') %>

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= ENV["PRODUCTION_DB_NAME"] %>
  username: <%= ENV["PRODUCTION_DB_USERNAME"] %>
  password: <%= Rails.application.credentials.gcp[:db_password] %>
  host: "<%= ENV.fetch("DB_SOCKET_DIR") { '/cloudsql' } %>/<%= ENV["CLOUD_SQL_CONNECTION_NAME"] %>"