development:
  url: <%= ENV.fetch("DATABASE_URL","?").gsub('?', '_development?') %>

test:
  url: <%= ENV.fetch("DATABASE_URL","?").gsub('?', '_test?') %>

staging:
  url: <%= ENV.fetch("DATABASE_URL","?").gsub('?', '_staging?') %>

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= Rails.application.credentials.gcp.fetch(:db_passsword, "") %>
  host: "<%= ENV.fetch("DATABASE_SOCKET_DIR") { '/cloudsql' } %>/<%= ENV["CLOUD_SQL_CONNECTION_NAME"] %>"