name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  STORAGE_CREDENTIALS : ${{ secrets.STORAGE_CREDENTIALS }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests!
        run: -|
          docker compose build --build-arg="RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}" \
          docker compose run -e portfolio rails test --verbose --pride