name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  STORAGE_CREDENTIALS : ${{ secrets.STORAGE_CREDENTIALS }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --build -e "RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}" -e "RAILS_ENV=test" portfolio bash -c "rails db:create && rails db:migrate && rails test --verbose --pride"