name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  STORAGE_CREDENTIALS : ${{ secrets.STORAGE_CREDENTIALS }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker compose build --build-arg="RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}"
      - name: Create Database
        run: docker compose run -e "RAILS_ENV=test" portfolio rails db:create
      - name: Migrate Database
        run: docker compose run -e "RAILS_ENV=test" portfolio rails db:migrate
      - name: Test
        run: docker compose run -e "RAILS_ENV=test"  portfolio rails test --verbose --pride